name = "Infino"
uuid = "fb86a6d0-8469-4260-849d-6419c6b51222"
authors = ["Liwei Ji"]
version = "1.0.0-DEV"

[deps]
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
